cmake_minimum_required(VERSION 3.25)
string(RANDOM LENGTH 20 ALPHABET 0123456789abcdef run_id)
set(run "${OUTPUT_ROOT}/${MODE}-${run_id}")
file(MAKE_DIRECTORY "${run}")
file(READ "${FIXTURE}/manifest.json" manifest)
foreach(name IN ITEMS state inputs)
    file(READ "${FIXTURE}/${name}.json" ${name})
    file(SHA256 "${FIXTURE}/${name}.json" ${name}_sha)
    string(JSON expected GET "${manifest}" cases 0 ${name} sha256)
    if(NOT expected STREQUAL "${${name}_sha}")
        message(FATAL_ERROR "Oracle fixture identity changed: ${name}")
    endif()
endforeach()
string(JSON start GET "${state}" start_frame)
string(JSON end GET "${state}" end_frame)
string(JSON cut GET "${state}" cut_frame)
string(JSON looping GET "${state}" looping)
string(JSON duration GET "${state}" asset_seconds)
string(JSON frame GET "${inputs}" operations 0 frame)
string(JSON fps GET "${inputs}" operations 0 fps)
if(looping)
    set(looping 1)
else()
    set(looping 0)
endif()
if(MODE STREQUAL "invalid")
    set(frame "120extra")
endif()
execute_process(COMMAND "${TRIAL}" "${frame}" "${start}" "${end}" "${cut}" "${looping}"
    "${fps}" "${duration}" "${run}/decision.toml"
    RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 3)
file(WRITE "${run}/stdout.log" "${stdout}")
file(WRITE "${run}/stderr.log" "${stderr}")
if(MODE STREQUAL "invalid")
    if(NOT result EQUAL 1 OR NOT stderr MATCHES "invalid_number" OR EXISTS "${run}/decision.toml")
        message(FATAL_ERROR "Invalid argument did not fail before observation: ${run}")
    endif()
else()
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Reference adapter failed: ${stderr}; ${run}")
    endif()
    file(READ "${run}/decision.toml" decision)
    if(NOT decision MATCHES "action = \"restart\"" OR NOT decision MATCHES "offset_seconds = 1.5\n")
        message(FATAL_ERROR "Unexpected reference decision: ${run}")
    endif()
    foreach(entry IN ITEMS "${TRIAL}" "${SOURCE}" "${ADAPTER}" "${FIXTURE}/manifest.json")
        file(SHA256 "${entry}" identity)
        file(APPEND "${run}/decision.toml" "\n[[provenance]]\npath = '${entry}'\nsha256 = \"${identity}\"\n")
    endforeach()
    file(COPY "${FIXTURE}/state.json" "${FIXTURE}/inputs.json" DESTINATION "${run}")
endif()
message(STATUS "Reference decision evidence: ${run}")
