cmake_minimum_required(VERSION 3.25)
file(SHA256 "${INPUT}" input_sha)
if(NOT input_sha STREQUAL "5d764a90b6ae1b6606aa95bbd343c54fd1a7b3aa7f7f20e116afc53423081602")
    message(FATAL_ERROR "Input fixture changed")
endif()
file(SHA256 "${CMAKE_CURRENT_LIST_DIR}/data/common-mix.ay" pack_sha)
file(SHA256 "${CMAKE_CURRENT_LIST_DIR}/data/trust.toml" trust_sha)
if(NOT pack_sha STREQUAL "f9677125e2f7ec0d35efae5ec25bc967bab125721a6aeee685e8bd7cfcbd3691"
   OR NOT trust_sha STREQUAL "4714e9022cd40807c55f7ca1821e39db6c45389b0f15c3f9264c99b1e0d315fa")
    message(FATAL_ERROR "Synthetic pack or private test registry changed")
endif()
string(RANDOM LENGTH 20 ALPHABET 0123456789abcdef run_id)
set(run_dir "${OUTPUT_ROOT}/common-${MODE}-${run_id}")
file(MAKE_DIRECTORY "${run_dir}")
execute_process(COMMAND "${TRIAL}" "${INPUT}" "${run_dir}" "${MODE}" "${CMAKE_CURRENT_LIST_DIR}/data/common-mix.ay" "${CMAKE_CURRENT_LIST_DIR}/data/trust.toml"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 8)
file(WRITE "${run_dir}/stdout.log" "${output}")
file(WRITE "${run_dir}/stderr.log" "${error}")
set(expected 0)
if(MODE STREQUAL "gain_switch_loss")
    set(expected 6)
    if(NOT error MATCHES "transition_trace_incomplete")
        message(FATAL_ERROR "Lost gain transition was not diagnosed: ${run_dir}")
    endif()
endif()
if(MODE STREQUAL "prime_missing" OR MODE STREQUAL "prime_loss")
    set(expected 5)
    if(NOT error MATCHES "prime_alignment_incomplete")
        message(FATAL_ERROR "Lost prime alignment was not diagnosed: ${run_dir}")
    endif()
endif()
if(MODE STREQUAL "missing_contribution")
    set(expected 3)
    if(NOT error MATCHES "contribution_mismatch")
        message(FATAL_ERROR "Missing contribution was not diagnosed: ${run_dir}")
    endif()
endif()
if(MODE STREQUAL "drain_loss")
    set(expected 4)
    if(NOT error MATCHES "drain_incomplete")
        message(FATAL_ERROR "Lost pending audio was not diagnosed: ${run_dir}")
    endif()
endif()
if(NOT result STREQUAL "${expected}")
    message(FATAL_ERROR "Common mix failed: ${result} ${error}; evidence: ${run_dir}")
endif()
file(SIZE "${run_dir}/mix.f32le" size)
file(READ "${run_dir}/mix.toml" manifest)
string(REGEX MATCH "sample_count = ([0-9]+)" unused "${manifest}")
math(EXPR expected_size "${CMAKE_MATCH_1} * 8")
if(NOT size EQUAL expected_size OR size EQUAL 0 OR size GREATER 65536)
    message(FATAL_ERROR "Incomplete output: ${run_dir}")
endif()
file(SHA256 "${run_dir}/mix.f32le" output_sha)
file(SHA256 "${run_dir}/contributions.f32le" contributions_sha)
get_filename_component(binary_dir "${TRIAL}" DIRECTORY)
file(SHA256 "${binary_dir}/SDL3.dll" sdl_sha)
file(APPEND "${run_dir}/mix.toml"
    "\n[audit]\ninput_sha256 = \"${input_sha}\"\noutput_sha256 = \"${output_sha}\"\nsdl_sha256 = \"${sdl_sha}\"\ncontributions_sha256 = \"${contributions_sha}\"\npack_sha256 = \"${pack_sha}\"\ntrust_sha256 = \"${trust_sha}\"\n")
message(STATUS "Common mix evidence: ${run_dir}")
