cmake_minimum_required(VERSION 3.25)
file(SHA256 "${INPUT}" input_sha)
if(NOT input_sha STREQUAL "5d764a90b6ae1b6606aa95bbd343c54fd1a7b3aa7f7f20e116afc53423081602")
    message(FATAL_ERROR "Input fixture changed")
endif()
string(RANDOM LENGTH 20 ALPHABET 0123456789abcdef run_id)
set(run_dir "${OUTPUT_ROOT}/${MODE}-${FAULT}-${run_id}")
foreach(kind IN ITEMS reference observed)
    file(MAKE_DIRECTORY "${run_dir}/${kind}")
    string(TOUPPER "${kind}" executable_variable)
    set(fault_argument)
    if(kind STREQUAL "observed" AND FAULT)
        set(fault_argument "${FAULT}")
    endif()
    execute_process(COMMAND "${${executable_variable}}" "${INPUT}" "${run_dir}/${kind}" "${MODE}" ${fault_argument}
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 5)
    file(WRITE "${run_dir}/${kind}/stdout.log" "${output}")
    file(WRITE "${run_dir}/${kind}/stderr.log" "${error}")
    if(fault_argument)
        if(FAULT STREQUAL "drop")
            set(expected_error "coverage_incomplete")
        elseif(FAULT STREQUAL "reset_drop")
            set(expected_error "reset_observation_missing")
        elseif(FAULT STREQUAL "reset_phase")
            set(expected_error "reset_state_invalid")
        else()
            set(expected_error "phase_conservation_failed")
        endif()
        if(NOT result STREQUAL "1" OR NOT error MATCHES "conversion_probe_failed: ${expected_error}")
            message(FATAL_ERROR "Trace fault was not rejected as expected: ${error}; ${run_dir}")
        endif()
        message(STATUS "Conversion negative evidence: ${run_dir}")
        return()
    endif()
    if(NOT result STREQUAL "0")
        message(FATAL_ERROR "${kind}: ${result} ${error}; evidence: ${run_dir}")
    endif()
    file(SHA256 "${run_dir}/${kind}/conversion.f32le" ${kind}_sha)
    get_filename_component(binary_dir "${${executable_variable}}" DIRECTORY)
    file(SHA256 "${binary_dir}/SDL3.dll" ${kind}_sdl_sha)
    file(APPEND "${run_dir}/${kind}/conversion.toml"
        "\n[audit]\ninput_sha256 = \"${input_sha}\"\noutput_sha256 = \"${${kind}_sha}\"\nsdl_sha256 = \"${${kind}_sdl_sha}\"\n")
endforeach()
if(NOT reference_sdl_sha STREQUAL "90616fefb7076606b9088e683172d87ae3776c76a7b4df0cb62e429c96583eed")
    message(FATAL_ERROR "Reference SDL distribution changed")
endif()
if(NOT reference_sha STREQUAL observed_sha)
    message(FATAL_ERROR "Observed conversion differs from the published reference: ${run_dir}")
endif()
message(STATUS "Conversion phase evidence: ${run_dir}")
