cmake_minimum_required(VERSION 3.25)
string(RANDOM LENGTH 20 ALPHABET 0123456789abcdef run_id)
get_filename_component(fixture_dir "${PACK}" DIRECTORY)
set(trust "${fixture_dir}/trust.toml")
file(SHA256 "${PACK}" pack_sha)
file(SHA256 "${trust}" trust_sha)
if(NOT pack_sha STREQUAL "f9677125e2f7ec0d35efae5ec25bc967bab125721a6aeee685e8bd7cfcbd3691"
   OR NOT trust_sha STREQUAL "4714e9022cd40807c55f7ca1821e39db6c45389b0f15c3f9264c99b1e0d315fa")
    message(FATAL_ERROR "Staging fixture changed")
endif()
set(run_dir "${OUTPUT_ROOT}/${MODE}-${run_id}")
set(resume_args)
if(MODE MATCHES "^resume_")
    get_filename_component(fixture "${CMAKE_CURRENT_LIST_DIR}/../../../../specs/001-AYTHER-bug-audio-qa/evidence/qa-021-oracle-definition" ABSOLUTE)
    file(READ "${fixture}/manifest.json" definition)
    foreach(name IN ITEMS state inputs)
        file(READ "${fixture}/${name}.json" ${name})
        file(SHA256 "${fixture}/${name}.json" identity)
        string(JSON expected GET "${definition}" cases 0 ${name} sha256)
        if(NOT expected STREQUAL identity)
            message(FATAL_ERROR "Resume fixture identity changed")
        endif()
    endforeach()
    string(JSON frame GET "${inputs}" operations 0 frame)
    string(JSON fps GET "${inputs}" operations 0 fps)
    foreach(name IN ITEMS start_frame end_frame cut_frame looping asset_seconds)
        string(JSON ${name} GET "${state}" ${name})
    endforeach()
    if(looping)
        set(looping 1)
    else()
        set(looping 0)
    endif()
    set(resume_args "${frame}" "${start_frame}" "${end_frame}" "${cut_frame}" "${looping}" "${fps}" "${asset_seconds}")
    file(COPY "${fixture}/state.json" "${fixture}/inputs.json" DESTINATION "${run_dir}")
endif()
foreach(kind IN ITEMS reference observed)
    file(MAKE_DIRECTORY "${run_dir}/${kind}")
    if(kind STREQUAL "reference")
        set(executable "${REFERENCE}")
    else()
        set(executable "${OBSERVED}")
    endif()
    execute_process(COMMAND "${executable}" "${run_dir}/${kind}" "${MODE}" "${PACK}" "${trust}" ${resume_args}
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 5)
    file(WRITE "${run_dir}/${kind}/stdout.log" "${output}")
    file(WRITE "${run_dir}/${kind}/stderr.log" "${error}")
    set(expected 0)
    if(kind STREQUAL "observed" AND (MODE STREQUAL "lost" OR MODE STREQUAL "voice_lost" OR MODE STREQUAL "resume_lost"))
        set(expected 2)
        if(NOT error MATCHES "staging_trace_incomplete")
            message(FATAL_ERROR "Lost staging record was not diagnosed: ${run_dir}")
        endif()
    endif()
    if(NOT result STREQUAL "${expected}")
        message(FATAL_ERROR "Staging failed: ${result} ${error}; ${run_dir}")
    endif()
    file(SHA256 "${run_dir}/${kind}/input.s16le" ${kind}_input)
    file(SHA256 "${run_dir}/${kind}/mix.f32le" ${kind}_output)
    file(SHA256 "${executable}" executable_sha)
    get_filename_component(bin_dir "${executable}" DIRECTORY)
    file(SHA256 "${bin_dir}/SDL3.dll" sdl_sha)
    file(APPEND "${run_dir}/${kind}/staging.toml" "\n[audit]\nexecutable_sha256 = \"${executable_sha}\"\nsdl_sha256 = \"${sdl_sha}\"\ninput_sha256 = \"${${kind}_input}\"\noutput_sha256 = \"${${kind}_output}\"\n")
endforeach()
if(NOT reference_input STREQUAL observed_input OR NOT reference_output STREQUAL observed_output)
    message(FATAL_ERROR "Staging observation changed reference PCM: ${run_dir}")
endif()
message(STATUS "Staging evidence: ${run_dir}")
