//! Type-safe C++ bindings generated with `cxx`.
//!
//! Bridge functions forward to the native Rust implementations and translate
//! bridge-compatible data structures without exposing Rust layout details.

// The bridge module must retain this name because downstream C++ bindings and
// generated Rust paths refer to `ffi::ffi`.
#![expect(
    clippy::module_inception,
    reason = "the cxx bridge module name is part of the generated binding contract"
)]

// ---------------------------------------------------------------------------
// ffi.rs — cxx::bridge for ayther_core
//
// Replaces the hand-written `extern "C"` wrappers in lib.rs with
// type-safe bindings generated at build time by cxx_build.
//
// ## Design: free functions throughout
//
// cxx::bridge method syntax (`fn foo(self: &T)`) requires a method named
// `foo` on the concrete type.  Several types already have methods with the
// same names but different signatures (e.g. TileHasher::last_occurrences
// returns &[native::TileOccurrence], not Vec<ffi::TileOccurrence>).
//
// To avoid conflicts every bridge entry is a prefixed free function:
//   tile_hasher_*   — TileHasher operations
//   tile_sub_*      — TileSubstitutor operations
//   script_*        — ScriptEnv operations
//
// The free-function implementations below forward to the real methods,
// converting between ffi types and native types where needed.
//
// ## What is NOT bridged here (kept as extern "C" in lib.rs)
//
//   process_frame   — takes *const u8 pixel buffer; keep raw for zero-copy
//   update_ram      — takes *const u8 RAM slice; same reason
//   set_pack        — pack pointer shared between two Rust objects
//   load_from_pack  — same reason
//
// ## C++ usage
//
//   #include "ayther_core/src/ffi.rs.h"  // generated by cxx_build
//
//   auto hasher = ayther::new_tile_hasher();
//   auto sub    = ayther::new_tile_substitutor();
//   auto occs   = ayther::tile_hasher_last_occurrences(*hasher);
//   ayther::tile_sub_add_override(*sub, 0xdeadbeefull, "hd/tiles/ground.png");
//   auto subs   = ayther::tile_sub_resolve(*sub, occs);
//   for (auto& s : subs) {... }
// ---------------------------------------------------------------------------
// Type re-exports — cxx::bridge resolves opaque Rust type names relative to
// the module that *contains* the bridge macro, i.e. this file's module scope
// (ayther_core::ffi).  Bring the real types into scope so cxx's generated
// `use super::TileHasher` etc. resolves correctly.
// ---------------------------------------------------------------------------

use crate::script_env::ScriptEnv;
use crate::sprite_hasher::TileHasher;
use crate::tile_substitutor::TileSubstitutor;
use crate::vram_sprite::SpriteHasher;
use crate::vram_sprite::SpriteSubstitutor;

#[cxx::bridge(namespace = "ayther")]
/// Types and declarations shared with C++ through `cxx`.
pub mod ffi {
    // -----------------------------------------------------------------------
    // Shared value types — visible to both C++ and Rust.
    // -----------------------------------------------------------------------

    /// Per-frame tile occurrence: tile-grid position + xxHash3-64 fingerprint.
    #[derive(Clone, Debug)]
    struct TileOccurrence {
        /// Luma-normalized tile hash.
        hash: u64,
        /// Column in the native tile grid.
        tile_x: u32,
        /// Row in the native tile grid.
        tile_y: u32,
    }

    /// One resolved HD substitution: blit `asset_path` at (tile_x, tile_y).
    #[derive(Clone, Debug)]
    struct TileSub {
        /// Logical path inside the.ay pack, e.g. "hd/tiles/ground.png".
        asset_path: String,
        /// Column in the native tile grid.
        tile_x: u32,
        /// Row in the native tile grid.
        tile_y: u32,
    }

    /// A tile override registered by Lua `ayther.tiles.replace()`.
    #[derive(Clone, Debug)]
    struct TileOverride {
        /// Tile hash to replace.
        hash: u64,
        /// Logical replacement asset path.
        asset_path: String,
    }

    /// Per-frame sprite occurrence from the VDP SAT — position-independent hash.
    #[derive(Clone, Debug)]
    struct SpriteOccurrence {
        /// Palette- and flip-independent sprite pattern hash.
        hash: u64,
        /// Detected animation-group identifier, or zero.
        anim_group_id: u64,
        /// Sprite width in native tiles.
        w_tiles: u8,
        /// Sprite height in native tiles.
        h_tiles: u8,
        /// Horizontal screen position in pixels.
        screen_x: i16,
        /// Vertical screen position in pixels.
        screen_y: i16,
        /// SAT chain link.
        link: u8, // SAT link field (metasprite grouping hint, R1.5)
        /// VDP palette line.
        palette: u8, // VDP palette index 0–3 (R1.5)
        /// VDP priority bit.
        priority: u8, // VDP priority bit (metasprite front/back)
        /// VDP horizontal-flip bit.
        hflip: u8, // VDP h-flip (0/1)
        /// VDP vertical-flip bit.
        vflip: u8,
    }

    /// One resolved HD sprite substitution.
    #[derive(Clone, Debug)]
    struct SpriteSub {
        /// Logical replacement asset path.
        asset_path: String,
        /// Horizontal destination position in pixels.
        screen_x: i16,
        /// Vertical destination position in pixels.
        screen_y: i16,
        /// Destination width in native tiles.
        w_tiles: u8,
        /// Destination height in native tiles.
        h_tiles: u8,
    }

    // -----------------------------------------------------------------------
    // Opaque Rust types exposed to C++ as UniquePtr<T>.
    // Free functions only — no method syntax — to avoid naming conflicts
    // with existing Rust methods that use native (non-ffi) types.
    // -----------------------------------------------------------------------
    extern "Rust" {

        // ---- TileHasher ----------------------------------------------------
        type TileHasher;

        /// Create a new TileHasher.
        fn new_tile_hasher() -> Box<TileHasher>;

        /// Total unique tiles accumulated since creation.
        fn tile_hasher_unique_count(h: &TileHasher) -> u32;

        /// All tile occurrences from the most-recently-processed frame.
        fn tile_hasher_last_occurrences(h: &TileHasher) -> Vec<TileOccurrence>;

        /// Write the tile catalog to a TOML file.  Returns true on success.
        fn tile_hasher_dump_toml(h: &TileHasher, path: &str) -> bool;

        // ---- TileSubstitutor -----------------------------------------------
        type TileSubstitutor;

        /// Create a new TileSubstitutor.
        fn new_tile_substitutor() -> Box<TileSubstitutor>;

        /// Register a Lua-driven runtime override.  Overrides beat the catalog.
        fn tile_sub_add_override(ts: Pin<&mut TileSubstitutor>, hash: u64, asset_path: &str);

        /// Clear all Lua-registered overrides (call once per frame).
        fn tile_sub_clear_overrides(ts: Pin<&mut TileSubstitutor>);

        /// Number of catalog entries loaded from tile_substitutions.toml.
        fn tile_sub_catalog_len(ts: &TileSubstitutor) -> usize;

        /// Resolve occurrences to HD substitution instructions.
        fn tile_sub_resolve(ts: &TileSubstitutor, occs: &[TileOccurrence]) -> Vec<TileSub>;

        // ---- ScriptEnv  (tile / frame APIs only) ---------------------------
        type ScriptEnv;

        /// Push tile occurrences so `ayther.tiles.list()` works in callbacks.
        /// Takes &ScriptEnv because ScriptEnv uses interior mutability (mlua).
        fn script_update_tiles(env: &ScriptEnv, occs: &[TileOccurrence]);

        /// Read tile overrides from `ayther._tile_overrides` (post-callback).
        /// Returns (hash, asset_path) pairs registered by `ayther.tiles.replace()`.
        fn script_get_tile_overrides(env: &ScriptEnv) -> Vec<TileOverride>;

        // ---- SpriteHasher --------------------------------------------------
        type SpriteHasher;

        /// Create a new SpriteHasher.
        fn new_sprite_hasher() -> Box<SpriteHasher>;

        /// Process one VRAM frame and return the number of new unique sprites.
        /// `sat_base`: usize::MAX auto-detects the SAT base from VRAM (recommended).
        fn sprite_hasher_process_vram(
            h: Pin<&mut SpriteHasher>,
            vram: &[u8],
            sat_base: usize,
        ) -> u32;

        /// Total unique sprite patterns accumulated since creation.
        fn sprite_hasher_unique_count(h: &SpriteHasher) -> u32;

        /// All sprite occurrences from the most-recently-processed frame.
        fn sprite_hasher_last_occurrences(h: &SpriteHasher) -> Vec<SpriteOccurrence>;

        // ---- SpriteSubstitutor ---------------------------------------------
        type SpriteSubstitutor;

        /// Create a new SpriteSubstitutor.
        fn new_sprite_substitutor() -> Box<SpriteSubstitutor>;

        /// Register a runtime override (e.g. from a Lua script).
        fn sprite_sub_add_override(ts: Pin<&mut SpriteSubstitutor>, hash: u64, asset_path: &str);

        /// Clear all runtime overrides (call once per frame).
        fn sprite_sub_clear_overrides(ts: Pin<&mut SpriteSubstitutor>);

        /// Number of entries loaded from `sprite_substitutions.toml`.
        fn sprite_sub_catalog_len(ts: &SpriteSubstitutor) -> usize;

        /// Resolve sprite occurrences to HD substitution instructions.
        fn sprite_sub_resolve(ts: &SpriteSubstitutor, occs: &[SpriteOccurrence]) -> Vec<SpriteSub>;
    }
}

// ---------------------------------------------------------------------------
// Bridge adapter implementations — free functions
// ---------------------------------------------------------------------------
// Each function converts between ffi types and the native types used by the
// underlying Rust subsystems, then delegates to the real implementation.

use std::pin::Pin;

// ---- TileHasher ------------------------------------------------------------

/// Creates an empty native tile hasher for the C++ bridge.
pub fn new_tile_hasher() -> Box<crate::sprite_hasher::TileHasher> {
    Box::new(crate::sprite_hasher::TileHasher::new())
}

/// Returns the cumulative number of unique tiles.
pub fn tile_hasher_unique_count(h: &crate::sprite_hasher::TileHasher) -> u32 {
    h.unique_tile_count()
}

/// Copies the most recent native tile occurrences into bridge values.
pub fn tile_hasher_last_occurrences(
    h: &crate::sprite_hasher::TileHasher,
) -> Vec<ffi::TileOccurrence> {
    h.last_occurrences()
        .iter()
        .map(|o| ffi::TileOccurrence {
            hash: o.hash,
            tile_x: o.tile_x,
            tile_y: o.tile_y,
        })
        .collect()
}

/// Writes the tile catalog as TOML and reports success.
pub fn tile_hasher_dump_toml(h: &crate::sprite_hasher::TileHasher, path: &str) -> bool {
    h.dump_toml(path)
}

// ---- TileSubstitutor -------------------------------------------------------

/// Creates an empty native tile substitutor for the C++ bridge.
pub fn new_tile_substitutor() -> Box<crate::tile_substitutor::TileSubstitutor> {
    Box::new(crate::tile_substitutor::TileSubstitutor::new())
}

/// Registers a live tile override through the bridge.
pub fn tile_sub_add_override(
    ts: Pin<&mut crate::tile_substitutor::TileSubstitutor>,
    hash: u64,
    asset_path: &str,
) {
    // TileSubstitutor is Unpin (no PhantomPinned), so into_inner is safe.
    Pin::into_inner(ts).add_override(hash, asset_path.to_string());
}

/// Clears all live tile overrides.
pub fn tile_sub_clear_overrides(ts: Pin<&mut crate::tile_substitutor::TileSubstitutor>) {
    Pin::into_inner(ts).clear_overrides();
}

/// Returns the number of distinct tile hashes in the catalog.
pub fn tile_sub_catalog_len(ts: &crate::tile_substitutor::TileSubstitutor) -> usize {
    ts.catalog_len()
}

/// Resolves bridged tile occurrences into substitution instructions.
pub fn tile_sub_resolve(
    ts: &crate::tile_substitutor::TileSubstitutor,
    occs: &[ffi::TileOccurrence],
) -> Vec<ffi::TileSub> {
    let native: Vec<crate::sprite_hasher::TileOccurrence> = occs
        .iter()
        .map(|o| crate::sprite_hasher::TileOccurrence {
            hash: o.hash,
            tile_x: o.tile_x,
            tile_y: o.tile_y,
        })
        .collect();

    ts.resolve(&native)
        .into_iter()
        .map(|s| ffi::TileSub {
            asset_path: s.asset_path,
            tile_x: s.tile_x,
            tile_y: s.tile_y,
        })
        .collect()
}

// ---- ScriptEnv -------------------------------------------------------------

/// Copies bridged tile occurrences into the script environment.
pub fn script_update_tiles(env: &crate::script_env::ScriptEnv, occs: &[ffi::TileOccurrence]) {
    let native: Vec<crate::sprite_hasher::TileOccurrence> = occs
        .iter()
        .map(|o| crate::sprite_hasher::TileOccurrence {
            hash: o.hash,
            tile_x: o.tile_x,
            tile_y: o.tile_y,
        })
        .collect();
    env.update_tiles(&native);
}

/// Copies Lua tile overrides into bridge values.
pub fn script_get_tile_overrides(env: &crate::script_env::ScriptEnv) -> Vec<ffi::TileOverride> {
    env.get_tile_overrides()
        .into_iter()
        .map(|(hash, asset_path)| ffi::TileOverride { hash, asset_path })
        .collect()
}

// ---- SpriteHasher ----------------------------------------------------------

/// Creates an empty native sprite hasher for the C++ bridge.
pub fn new_sprite_hasher() -> Box<crate::vram_sprite::SpriteHasher> {
    Box::new(crate::vram_sprite::SpriteHasher::new())
}

/// Processes one VRAM frame through the native sprite hasher.
pub fn sprite_hasher_process_vram(
    h: Pin<&mut crate::vram_sprite::SpriteHasher>,
    vram: &[u8],
    sat_base: usize,
) -> u32 {
    Pin::into_inner(h).process_vram(vram, sat_base)
}

/// Returns the cumulative number of unique sprite patterns.
pub fn sprite_hasher_unique_count(h: &crate::vram_sprite::SpriteHasher) -> u32 {
    h.unique_sprite_count()
}

/// Copies the most recent native sprite occurrences into bridge values.
pub fn sprite_hasher_last_occurrences(
    h: &crate::vram_sprite::SpriteHasher,
) -> Vec<ffi::SpriteOccurrence> {
    h.last_occurrences()
        .iter()
        .map(|o| ffi::SpriteOccurrence {
            hash: o.hash,
            anim_group_id: o.anim_group_id,
            w_tiles: o.w_tiles,
            h_tiles: o.h_tiles,
            screen_x: o.screen_x,
            screen_y: o.screen_y,
            link: o.link,
            palette: o.palette,
            priority: o.priority,
            hflip: o.hflip,
            vflip: o.vflip,
        })
        .collect()
}

// ---- SpriteSubstitutor -----------------------------------------------------

/// Creates an empty native sprite substitutor for the C++ bridge.
pub fn new_sprite_substitutor() -> Box<crate::vram_sprite::SpriteSubstitutor> {
    Box::new(crate::vram_sprite::SpriteSubstitutor::new())
}

/// Registers a live sprite override through the bridge.
pub fn sprite_sub_add_override(
    ts: Pin<&mut crate::vram_sprite::SpriteSubstitutor>,
    hash: u64,
    asset_path: &str,
) {
    Pin::into_inner(ts).add_override(hash, asset_path.to_string());
}

/// Clears all live sprite overrides.
pub fn sprite_sub_clear_overrides(ts: Pin<&mut crate::vram_sprite::SpriteSubstitutor>) {
    Pin::into_inner(ts).clear_overrides();
}

/// Returns the number of sprite substitution entries.
pub fn sprite_sub_catalog_len(ts: &crate::vram_sprite::SpriteSubstitutor) -> usize {
    ts.catalog_len()
}

/// Resolves bridged sprite occurrences into substitution instructions.
pub fn sprite_sub_resolve(
    ts: &crate::vram_sprite::SpriteSubstitutor,
    occs: &[ffi::SpriteOccurrence],
) -> Vec<ffi::SpriteSub> {
    let native: Vec<crate::vram_sprite::SpriteOccurrence> = occs
        .iter()
        .map(|o| crate::vram_sprite::SpriteOccurrence {
            hash: o.hash,
            anim_group_id: o.anim_group_id,
            w_tiles: o.w_tiles,
            h_tiles: o.h_tiles,
            screen_x: o.screen_x,
            screen_y: o.screen_y,
            link: o.link,
            palette: o.palette,
            priority: o.priority,
            slot: 0, // ruta cxx (resolve) no usa el slot SAT
            hflip: 0,
            vflip: 0, // CU-AN-11 (ruta cxx no aplica flip)
        })
        .collect();

    ts.resolve(&native)
        .into_iter()
        .map(|s| ffi::SpriteSub {
            asset_path: s.asset_path,
            screen_x: s.screen_x,
            screen_y: s.screen_y,
            w_tiles: s.w_tiles,
            h_tiles: s.h_tiles,
        })
        .collect()
}
