cmake_minimum_required(VERSION 3.25)
string(RANDOM LENGTH 20 ALPHABET 0123456789abcdef run_id)
set(run_dir "${OUTPUT_ROOT}/${MODE}-${run_id}")
foreach(kind IN ITEMS reference observed)
    file(MAKE_DIRECTORY "${run_dir}/${kind}")
    if(kind STREQUAL "reference")
        set(executable "${REFERENCE}")
    else()
        set(executable "${OBSERVED}")
    endif()
    execute_process(COMMAND "${executable}" "${run_dir}/${kind}" "${MODE}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 3)
    file(WRITE "${run_dir}/${kind}/stdout.log" "${output}")
    file(WRITE "${run_dir}/${kind}/stderr.log" "${error}")
    set(expected 0)
    if(kind STREQUAL "observed" AND MODE STREQUAL "lost")
        set(expected 2)
        if(NOT error MATCHES "voice_trace_incomplete")
            message(FATAL_ERROR "Lost voice record was not diagnosed: ${run_dir}")
        endif()
    endif()
    if(NOT result STREQUAL "${expected}")
        message(FATAL_ERROR "Voice experiment failed: ${result} ${error}; ${run_dir}")
    endif()
    file(SIZE "${run_dir}/${kind}/mixer.s16le" size)
    if(NOT size EQUAL 4096)
        message(FATAL_ERROR "Mixer output incomplete: ${run_dir}")
    endif()
    file(SHA256 "${run_dir}/${kind}/mixer.s16le" ${kind}_sha)
    file(SHA256 "${executable}" executable_sha)
    file(APPEND "${run_dir}/${kind}/voices.toml" "\n[audit]\nexecutable_sha256 = \"${executable_sha}\"\noutput_sha256 = \"${${kind}_sha}\"\n")
endforeach()
if(NOT reference_sha STREQUAL observed_sha)
    message(FATAL_ERROR "Observation changed reference PCM: ${run_dir}")
endif()
message(STATUS "Voice evidence: ${run_dir}")
