cmake_minimum_required(VERSION 3.25)
string(RANDOM LENGTH 20 ALPHABET 0123456789abcdef run_id)
set(run "${OUTPUT_ROOT}/${MODE}-${run_id}")
if(MODE MATCHES "^(internal|claimed)(_repeat)?$")
    foreach(kind IN ITEMS reference observed current current_observed)
        file(MAKE_DIRECTORY "${run}/${kind}")
        if(kind STREQUAL "reference")
            set(exe "${REFERENCE}")
        elseif(kind STREQUAL "observed")
            set(exe "${OBSERVED}")
        elseif(kind STREQUAL "current")
            set(exe "${CURRENT}")
        else()
            set(exe "${CURRENT_OBSERVED}")
        endif()
        execute_process(COMMAND "${exe}" "${run}/${kind}" "${MODE}"
            RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 3)
        file(WRITE "${run}/${kind}/stdout.log" "${output}")
        file(WRITE "${run}/${kind}/stderr.log" "${error}")
        if(kind STREQUAL "current" OR kind STREQUAL "current_observed")
            if(NOT result STREQUAL "0")
                message(FATAL_ERROR "Corrected rejection failed: ${result} ${error}; ${run}")
            endif()
        else()
            if(NOT result STREQUAL "1" OR NOT error MATCHES "rejection_created_instance")
                message(FATAL_ERROR "Historical defect not reproduced: ${result} ${error}; ${run}")
            endif()
        endif()
    endforeach()
    file(SHA256 "${run}/current/stderr.log" current_log)
    file(SHA256 "${run}/current_observed/stderr.log" observed_log)
    if(NOT current_log STREQUAL observed_log)
        message(FATAL_ERROR "Observation changed rejection counters: ${run}")
    endif()
    message(STATUS "Rejection before/after evidence: ${run}")
    return()
endif()
foreach(kind IN ITEMS reference observed)
    file(MAKE_DIRECTORY "${run}/${kind}")
    if(kind STREQUAL "reference")
        set(exe "${REFERENCE}")
    else()
        set(exe "${OBSERVED}")
    endif()
    execute_process(COMMAND "${exe}" "${run}/${kind}" "${MODE}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 3)
    file(WRITE "${run}/${kind}/stdout.log" "${output}")
    file(WRITE "${run}/${kind}/stderr.log" "${error}")
    set(expected 0)
    if(kind STREQUAL "observed" AND MODE STREQUAL "lost")
        set(expected 2)
        if(NOT error MATCHES "continuity_trace_incomplete")
            message(FATAL_ERROR "Missing gate was not diagnosed")
        endif()
    endif()
    if(NOT result STREQUAL "${expected}")
        message(FATAL_ERROR "Continuity failed: ${result} ${error}; ${run}")
    endif()
    file(SHA256 "${run}/${kind}/run.toml" ${kind}_state)
    file(SHA256 "${run}/${kind}/output.s16le" ${kind}_pcm)
    file(SHA256 "${exe}" exe_sha)
    file(APPEND "${run}/${kind}/trace.toml" "\n[audit]\nexecutable_sha256 = \"${exe_sha}\"\n")
endforeach()
if(NOT reference_state STREQUAL observed_state OR NOT reference_pcm STREQUAL observed_pcm)
    message(FATAL_ERROR "Observation changed state or PCM: ${run}")
endif()
message(STATUS "Continuity evidence: ${run}")
