#pragma once

// Stable umbrella for the Runtime-facing C++ Engine contract. Public modules
// are added here only after their ownership, lifetime, threading, and error
// rules have been specified and tested.
#include <ayther/ayther_layers.h>
#include <ayther/ayther_renderer.h>
#include <ayther/ayther_session.h>
#include <ayther/engine/audio_fact_queue.hpp>
#include <ayther/engine/audio_hd_state.hpp>
#include <ayther/engine/audio_initial_snapshot.hpp>
#include <ayther/engine/audio_observation_close.hpp>
#include <ayther/engine/audio_observation_overflow.hpp>
#include <ayther/engine/audio_observation_worker.hpp>
#include <ayther/engine/audio_observer.hpp>
#include <ayther/engine/audio_pcm_queue.hpp>
#include <ayther/engine/audio_production_limit.hpp>
#include <ayther/engine/capabilities.hpp>
#include <ayther/engine/core_probe.hpp>
#include <ayther/engine/input.hpp>
#include <ayther/engine/music_analysis_limits.hpp>
#include <ayther/engine/music_analysis_snapshot.hpp>
#include <ayther/engine/music_asset_owner.hpp>
#include <ayther/engine/music_audio_math.hpp>
#include <ayther/engine/music_causal_recognizer.hpp>
#include <ayther/engine/music_corpus_quality.hpp>
#include <ayther/engine/music_event_normalization.hpp>
#include <ayther/engine/music_event_scoring.hpp>
#include <ayther/engine/music_execution_adapter.hpp>
#include <ayther/engine/music_identity_state.hpp>
#include <ayther/engine/music_late_entry.hpp>
#include <ayther/engine/music_live_recognition.hpp>
#include <ayther/engine/music_pack_contract.hpp>
#include <ayther/engine/music_pattern_analysis.hpp>
#include <ayther/engine/music_pause_signal.hpp>
#include <ayther/engine/music_pause_state.hpp>
#include <ayther/engine/music_position_recovery.hpp>
#include <ayther/engine/music_proposal_assessment.hpp>
#include <ayther/engine/music_recognition_candidate.hpp>
#include <ayther/engine/music_sequence.hpp>
#include <ayther/engine/music_sequence_validation.hpp>
#include <ayther/engine/music_source_lifecycle.hpp>
#include <ayther/engine/music_transition_arbiter.hpp>
#include <ayther/engine/music_transition_cancel.hpp>
#include <ayther/engine/music_transition_queue.hpp>
#include <ayther/engine/music_transition_span.hpp>
#include <ayther/engine/music_voice_budget.hpp>
#include <ayther/engine/pack.hpp>
#include <ayther/engine/vulkan_interop.hpp>
