cmake_minimum_required(VERSION 3.25)
string(RANDOM LENGTH 20 ALPHABET 0123456789abcdef run_id)
set(run "${OUTPUT_ROOT}/${MODE}-${run_id}")
foreach(kind IN ITEMS reference observed)
    file(MAKE_DIRECTORY "${run}/${kind}")
    if(kind STREQUAL "reference")
        set(exe "${REFERENCE}")
    else()
        set(exe "${OBSERVED}")
    endif()
    execute_process(COMMAND "${exe}" "${run}/${kind}" "${MODE}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 3)
    file(WRITE "${run}/${kind}/stdout.log" "${output}")
    file(WRITE "${run}/${kind}/stderr.log" "${error}")
    set(expected 0)
    if(kind STREQUAL "observed" AND MODE STREQUAL "lost")
        set(expected 2)
        if(NOT error MATCHES "selection_trace_incomplete")
            message(FATAL_ERROR "Missing candidate was not diagnosed")
        endif()
    endif()
    if(NOT result STREQUAL "${expected}")
        message(FATAL_ERROR "Selection capture failed: ${result} ${error}; ${run}")
    endif()
    foreach(name IN ITEMS state input decision)
        file(SHA256 "${run}/${kind}/${name}.toml" ${kind}_${name})
    endforeach()
    file(SHA256 "${exe}" exe_sha)
    file(APPEND "${run}/${kind}/facts.toml" "\n[audit]\nexecutable_sha256 = \"${exe_sha}\"\n")
endforeach()
foreach(name IN ITEMS state input decision)
    if(NOT reference_${name} STREQUAL observed_${name})
        message(FATAL_ERROR "Observation changed ${name}: ${run}")
    endif()
endforeach()
message(STATUS "Selection reference evidence: ${run}")
