cmake_minimum_required(VERSION 3.25)
file(SHA256 "${INPUT}" input_sha)
if(NOT input_sha STREQUAL "5d764a90b6ae1b6606aa95bbd343c54fd1a7b3aa7f7f20e116afc53423081602")
    message(FATAL_ERROR "Controlled PCM identity differs from QA-014")
endif()
string(RANDOM LENGTH 20 ALPHABET 0123456789abcdef run_id)
set(run_dir "${OUTPUT_ROOT}/${MODE}-${run_id}")
file(MAKE_DIRECTORY "${run_dir}")
execute_process(COMMAND "${TRIAL}" "${INPUT}" "${run_dir}" "${MODE}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 8)
file(WRITE "${run_dir}/stdout.log" "${output}")
file(WRITE "${run_dir}/stderr.log" "${error}")
if(MODE STREQUAL "known" OR MODE STREQUAL "auxiliary" OR MODE STREQUAL "prime" OR MODE STREQUAL "conversion" OR MODE STREQUAL "closing")
    set(expected_result "0")
elseif(MODE STREQUAL "auxiliary_missing" OR MODE STREQUAL "prime_missing" OR MODE STREQUAL "conversion_missing")
    set(expected_result "4")
else()
    set(expected_result "3")
endif()
if(NOT result STREQUAL expected_result)
    message(FATAL_ERROR "Trial failed: ${result}: ${output} ${error}; evidence: ${run_dir}")
endif()
foreach(name IN ITEMS capture.f32le capture.toml)
    if(NOT EXISTS "${run_dir}/${name}")
        message(FATAL_ERROR "Missing real capture artifact: ${name}")
    endif()
endforeach()
file(READ "${run_dir}/capture.toml" manifest)
file(SIZE "${run_dir}/capture.f32le" size)
string(REGEX MATCH "sample_count = ([0-9]+)" unused "${manifest}")
math(EXPR expected_size "${CMAKE_MATCH_1} * 2 * 4")
if(MODE MATCHES "^closing")
    set(minimum_size 8192)
else()
    set(minimum_size 131072)
endif()
if(NOT size EQUAL expected_size OR size LESS minimum_size)
    message(FATAL_ERROR "Capture sample range does not match the retained bytes")
endif()
file(SHA256 "${run_dir}/capture.f32le" output_sha)
file(APPEND "${run_dir}/capture.toml"
    "\n[audit]\ninput_fixture_sha256 = \"${input_sha}\"\noutput_sha256 = \"${output_sha}\"\nbyte_count = ${size}\n")
message(STATUS "Main capture evidence: ${run_dir}")
